# Generated by Django 4.0.1 on 2022-01-25 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0002_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pais.pais'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pais.estado'),
        ),
    ]
