# Generated by Django 4.0.1 on 2022-01-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superusuario', models.BooleanField(default=False)),
                ('administrador', models.BooleanField(default=False)),
                ('empleado', models.BooleanField(default=False)),
            ],
        ),
    ]
