# Generated by Django 4.0.1 on 2022-01-19 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('apellido', models.CharField(max_length=300)),
                ('direccion', models.CharField(max_length=300)),
                ('telefono', models.IntegerField(default=1)),
                ('correo', models.EmailField(max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='usuario/')),
                ('tipo', models.CharField(choices=[('s', 'superusuario'), ('a', 'administrador'), ('e', 'empleado')], max_length=1)),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pais.pais')),
            ],
        ),
    ]
