# Generated by Django 4.0.1 on 2022-01-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sede', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='estado',
            field=models.CharField(choices=[('a', 'Activo'), ('i', 'Inactivo')], max_length=1),
        ),
    ]
