# Generated by Django 4.0.1 on 2022-01-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sede', '0002_alter_sede_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='image',
            field=models.ImageField(blank=True, upload_to='sede/'),
        ),
    ]
