# Generated by Django 4.0.1 on 2022-01-19 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pais', '0001_initial'),
        ('tipo_usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.IntegerField(default=1)),
                ('nom_empresa', models.CharField(max_length=300)),
                ('nom_comercial', models.CharField(max_length=300)),
                ('direccion', models.CharField(max_length=300)),
                ('telefono', models.IntegerField(default=1)),
                ('correo', models.EmailField(max_length=150)),
                ('web', models.URLField()),
                ('image', models.ImageField(blank=True, upload_to='empresa/')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pais.pais')),
                ('usuario_super', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipo_usuario.tipousuario')),
            ],
        ),
    ]
