# Generated by Django 4.0.1 on 2022-01-25 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0003_ciudad_pais_alter_ciudad_estado'),
        ('empresa', '0002_empresa_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pais.ciudad'),
        ),
    ]
